create or replace FUNCTION CALCULA_INSS (
                                         P_SALARIO IN NUMBER 
                                        ) RETURN NUMBER
 AS
--Declaração das variáveis da função 
V_FAIXAUM NUMBER := 0.075;
V_FAIXADOIS NUMBER := 0.09;
V_FAIXATRES NUMBER := 0.12;
V_FAIXAQUATRO NUMBER := 0.14;


 BEGIN  

        IF P_SALARIO <= 1212.00
            THEN 
            
                RETURN (P_SALARIO * V_FAIXAUM);
    
        ELSIF (P_SALARIO > 1212.00 AND P_SALARIO <= 2427.35)
            THEN
            
                RETURN (1212.00 * V_FAIXAUM) + (V_FAIXADOIS * (P_SALARIO - 1212.00));
                
        ELSIF (P_SALARIO > 2427.35 AND P_SALARIO <= 3641.03)
            THEN
            
                RETURN (1212.00 * V_FAIXAUM) + ((2427.35 - 1212.00)*V_FAIXADOIS) + (V_FAIXADOIS * (P_SALARIO - 2427.35));
                
        ELSIF (P_SALARIO > 3641.03 AND P_SALARIO <= 7087.22)
            THEN
            
                RETURN (1212.00 * V_FAIXAUM) + ((2427.35 - 1212.00) * V_FAIXADOIS) + ((3641.03 - 2427.35) * V_FAIXATRES) + (V_FAIXAQUATRO * (P_SALARIO - 3641.03));
        ELSE
                RETURN (1212.00 * V_FAIXAUM) + ((2427.35 - 1212.00) * V_FAIXADOIS) + ((3641.03 - 2427.35) * V_FAIXATRES) + ((7087.22 - 3641.03) * V_FAIXAQUATRO);
            
        END IF;    
        EXCEPTION
            WHEN OTHERS THEN 
            RAISE_APPLICATION_ERROR (-2001, SQLERRM);

 END;
 
 SELECT CALCULA_INSS(2500) FROM DUAL
 ;
 
 CREATE OR REPLACE FUNCTION CALCULA_IR (P_SALARIO IN NUMBER) RETURN NUMBER
 AS
 V_DESCONTO NUMBER := 0.0;
 BEGIN
 
 IF (P_SALARIO <= 1903.98)
    THEN
    RETURN ROUND(V_DESCONTO, 3);
 END IF;
 
 IF(P_SALARIO >= 1903.99 AND P_SALARIO <= 2826.65)
    THEN
    V_DESCONTO := ((P_SALARIO - (P_SALARIO * 0.925)) - 142.80);
    RETURN ROUND(V_DESCONTO, 3);
  END IF;
  
  IF(P_SALARIO >= 2826.66 AND P_SALARIO <= 3751.05)
    THEN
    V_DESCONTO := ((P_SALARIO - (P_SALARIO * 0.85)) - 354.80);
    RETURN ROUND(V_DESCONTO, 3);
  END IF;
  
  IF(P_SALARIO >= 3751.06 AND P_SALARIO <= 4664.68)
    THEN
    V_DESCONTO := ((P_SALARIO - (P_SALARIO * 0.775)) - 636.13);
    RETURN ROUND(V_DESCONTO, 3);
  END IF;
  
  IF(P_SALARIO >= 4664.69)
    THEN
    V_DESCONTO := ((P_SALARIO - (P_SALARIO * 0.775)) - 869.36);
    RETURN ROUND(V_DESCONTO, 3);
  END IF; 
 
 END;
 
 SELECT CALCULA_IR(2500)
   FROM DUAL
;

CREATE OR REPLACE FUNCTION CALCULA_DESCONTOS
(
    P_SALARIO IN NUMBER
)
    RETURN NUMBER
    AS
        V_DESCONTO_IR NUMBER;
        V_DESCONTO_INSS NUMBER;
        V_DESCONTOS NUMBER;
        BEGIN
            
            V_DESCONTO_IR := CALCULA_IR(P_SALARIO);
            V_DESCONTO_INSS := CALCULA_INSS(P_SALARIO);
            V_DESCONTOS := V_DESCONTO_IR + V_DESCONTO_INSS;
            
            
            RETURN ROUND(V_DESCONTOS ,2);
END;

SELECT CALCULA_DESCONTOS(2500)
  FROM DUAL
;